// Generated by https://quicktype.io

export interface DirectionsAPIResponse {
   routes: Route[]
   waypoints: Waypoint[]
   code: string
   uuid: string
}

export interface Route {
   weight_name: string
   weight: number
   duration: number
   distance: number
   legs: Leg[]
   geometry: Geometry
}

export interface Geometry {
   coordinates: Array<[number, number]>
   type: string
}

export interface Leg {
   notifications: Notification[]
   admins: Admin[]
   weight: number
   duration: number
   distance: number
   summary: string
}

export interface Admin {
   iso_3166_1_alpha3: string
   iso_3166_1: string
}

export interface Notification {
   details: Details
   subtype: string
   type: string
   geometry_index_end: number
   geometry_index_start: number
}

export interface Details {
   message: string
}

export interface Waypoint {
   distance: number
   name: string
   location: number[]
}
